---
- name: Install OS Packages
  yum: 
    name: 
      - libselinux-python 
    state: present

- import_tasks: tarball.yml

- import_tasks: upstart.yml
  tags: deploy

- import_tasks: systemd.yml
  tags: deploy
